<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Better RSpec</string>
  <key>fileTypes</key>
  <array>
    <string>spec.rb</string>
  </array>
  <key>foldingStartMarker</key>
  <string>(?x)^
      (\s*+
          (module|class|def
          |unless|if
          |case
          |begin
          |for|while|until
       |^=begin
          |(  "(\\.|[^"])*+"          # eat a double quoted string
           | '(\\.|[^'])*+'        # eat a single quoted string
           |   [^#"']                # eat all but comments and strings
           )*
           (                        \s   (do|begin|case)
           | (?&lt;!\$)[-+=&amp;|*/~%^&lt;&gt;~] \s*+ (if|unless)
           )
          )\b
          (?! [^;]*+ ; .*? \bend\b )
      |(  "(\\.|[^"])*+"              # eat a double quoted string
       | '(\\.|[^'])*+'            # eat a single quoted string
       |   [^#"']                    # eat all but comments and strings
       )*
       ( \{ (?!  [^}]*+ \} )
       | \[ (?! [^\]]*+ \] )
       )
      ).*$
  |   [#] .*? \(fold\) \s*+ $         # Sune’s special marker
  </string>
  <key>foldingStopMarker</key>
  <string>(?x)
    (   (^|;) \s*+ end   \s*+ ([#].*)? $
    |   (^|;) \s*+ end \. .* $
    |   ^     \s*+ [}\]] \s*+ ([#].*)? $
    |   [#] .*? \(end\) \s*+ $    # Sune’s special marker
    |   ^=end
    )</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>(?&lt;!\.)\b(before|after|around|shared_examples|shared_context|it_behaves_like|include_examples|it_should_behave_like|it_has_behavior)\b(?![?!])</string>
      <key>name</key>
      <string>keyword.other.rspec</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#behaviour</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#pending</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#example</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#other</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#subject</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#subject-variable</string>
    </dict>
    <dict>
      <key>include</key>
      <string>source.ruby</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>behaviour</key>
    <dict>
      <key>begin</key>
      <string>^\s*(describe|context|feature)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec.behaviour</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\b(do)\s*$</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.ruby.start-block</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.rspec.behaviour</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ruby</string>
        </dict>
      </array>
    </dict>
    <key>example</key>
    <dict>
      <key>begin</key>
      <string>^\s*(it|its|specify|scenario|example|xit)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec.example</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\b(do)\s*$|{</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.ruby.start-block</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.rspec.example</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ruby</string>
        </dict>
      </array>
    </dict>
    <key>pending</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec.pending</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.ruby</string>
        </dict>
      </dict>
      <key>match</key>
      <string>^\s*(it|its|specify|scenario|example)\s+(.*\S)(?&lt;!do|})\s*$</string>
      <key>name</key>
      <string>meta.rspec.pending</string>
    </dict>
    <key>other</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(expect|double|allow|let|expect_any_instance_of|allow_any_instance_of|is_expected)\b</string>
    </dict>

    <key>subject</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(subject!?)(?:\s*[({])</string>
    </dict>

    <key>subject-variable</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.other.rspec</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(subject|described_class)(?!\s*[{(])\b</string>
    </dict>
  </dict>

  <key>scopeName</key>
  <string>source.ruby.rspec</string>
  <key>uuid</key>
  <string>EFA47EDA-F65D-45B9-9A3E-97366570FFB4</string>
</dict>
</plist>
